#!/bin/sh /etc/rc.common
START=50

# 定义路径变量
CRONTAB_FILE="/etc/crontabs/root"
CAMPUS_LOGIN_PATH="/usr/libexec/campus_login"

run_reboot()
{
    local enable
    config_get_bool enable $1 enable

    # 检查语法，添加空格
    if [ $enable = 1 ]; then
        local minute
        local hour
        local week
        config_get week $1 week
        config_get minute $1 minute
        config_get hour $1 hour

        # 合法性检查和处理
        if [ -z "$minute" ]; then
            echo "Error: minute configuration is missing."
            return 1
        fi
        if [ -z "$hour" ]; then
            echo "Error: hour configuration is missing."
            return 1
        fi
        if [ -z "$week" ]; then
            echo "Error: week configuration is missing."
            return 1
        fi

        if [ $minute = 0 ]; then
            minute="00"
        fi
        if [ $week = 7 ]; then
            week="*"
        fi

        # 移除包含指定字符串的 cron 任务
        crontab -l | grep -v "$CAMPUS_LOGIN_PATH" | crontab -

        # 添加新的 cron 任务
        echo "$minute $hour * * $week $CAMPUS_LOGIN_PATH" >> $CRONTAB_FILE
        echo "Auto REBOOT has started."
    else
        # 移除包含指定字符串的 cron 任务
        crontab -l | grep -v "$CAMPUS_LOGIN_PATH" | crontab -
        /etc/init.d/cron restart
        echo "Auto REBOOT has stopped."
    fi
}

start()
{
    config_load campus_network
    config_foreach run_reboot cron
}

stop()
{
    echo "Auto REBOOT has stopped."
}